### PR TITLE
Feature/branches

### LINKED ISSUE #38: Support for Branches API
I'm currently working on a feature to support the Branches API from Gitlab

### PR DESCRIPTION
**Pull request by dnagl**
Resolves #38

### CODE REVIEW

**Comment by nmklotas** [comment]
Hi, thanks for this! Can you check why the test fails? :)

**Comment by dnagl** [comment]
Hi, I'll have a look on the test results ;)

**Comment by dnagl** [comment]
@nmklotas The tests are now fixed - i used an int instead of an string for the projectId in one of the requests

**Comment by nmklotas** [comment]
Good! thanks!

**Pull request merged**
