### PR TITLE
Add runners and job models and some queries

### PR DESCRIPTION
**Pull request by jadentom**
Added runner and job models. Also added some API queries for both runners and jobs.

No unit tests. I get a "no main()" error when I try to run them so I haven't tried.

### CODE REVIEW

**Comment by casz** [comment]
link to see current commit author: https://github.com/nmklotas/GitLabApiClient/pull/93/commits/12cb9ca5e7ab6ef7e4451e7086598d4983764f76.patch

@jadentom 
You might want to set up an email alias on your GitHub account 🥇
https://help.github.com/articles/adding-an-email-address-to-your-github-account/

Or look into fixing your git user.email config 😅  
https://help.github.com/articles/setting-your-commit-email-address-in-git
then you would need to amend your commits: https://stackoverflow.com/a/3042512
after changing author

to get proper credit for your commits 🏆

**Comment by casz** [comment]
also build fails to compile on appveyor :)

**Comment by jadentom** [comment]
Thanks I'll check both of those out. It compiles as part of my project but
I probably should have submitted it as a draft anyways 😅.

**Comment by jadentom** [comment]
Closing to resubmit with amended commits.

**Comment by jadentom** [comment]
Fixed build. Also added alias to my account thanks @casz

**Comment by casz** [comment]
@jadentom perhaps you could improve the diff coverage? 🤔

**Comment by jadentom** [comment]
@casz not sure how to run the unit tests. I get a "no main()" error whenever I try.

**Comment by casz** [comment]
`dotnet test` should do the trick.

what IDE/editor are you using?

**Comment by casz** [comment]
https://github.com/nmklotas/GitLabApiClient/blob/2f20508c5185f1c02122d53dabaef5444698d301/test.ps1#L3

does the trick :)

**Comment by jadentom** [comment]
@casz 
image my bad, it's not that the tests don't run it's that I can't build in the first place. I'm on dotnet core 3.1.100 so that shouldn't be the issue.

**Comment by jadentom** [comment]
Although as a work-around dotnet test runs perfectly on my personal windows box. I guess I can use that for now.

**Comment by casz** [comment]
That error does not show up on in the GitHub CI which runs on ubuntu 18.04

**Comment by casz** [comment]
@jadentom what version of ubuntu are you using?

**Comment by jadentom** [comment]
@casz 16.04

**Comment by casz** [comment]
That might be your issue 🤔 I only tested this on 18.04

**Pull request merged**
