### PR TITLE
Added opportunity to retrieve merge request notes and time statistics

### PR DESCRIPTION
**Pull request by dremerdt**

### CODE REVIEW

**Comment by casz** [comment]
Your author does not your user you submitted the PR with: https://github.com/nmklotas/GitLabApiClient/commit/3201368e4c4bc33da879c1b02ab369bba4669d8d.patch

Also would you mind formatting the project, you can use the [dotnet format](https://github.com/dotnet/format) tool

**Comment by casz** [comment]
Would you mind resolving the conflicts?

**Comment by dremerdt** [comment]
> Would you mind resolving the conflicts?

resolved

**Comment by dremerdt** [comment]
> Would you mind resolving the conflicts?

Hi, resolved.

**Pull request merged**
