### PR TITLE
groups api client

### PR DESCRIPTION
**Pull request by ilijamitkov**
Adding groups api client

### CODE REVIEW

**Comment by nmklotas** [comment]
Hi,

Thanks for the PR!

**Comment by nmklotas** [comment]
This is very nice, Thanks!. Merged. I will fix some spacing/formatting issues, also remove some object type properties from requests/responses.

**Comment by nmklotas** [comment]
I've did some fixes and refactorings for your PR in #3

**Comment by ilijamitkov** [comment]
Hi,

Thanks one thing that I would like to change though is to always use curly brackets on conditions even in cases where they are not required its considered to be good practice...

**Comment by nmklotas** [comment]
Hi,

There's two schools of thought here. I choose the more readable approach always, if there's like 10 simple if's like in QueryBuilders then it might be more readable to not to use { }, lots of code lines might be saved, lots of %.

But if there's some other statements like:
```C#
    foreach(var obj in objects)
        try
        {
             //do something
        }
        catch(Exception ex)
        {
        }

 { } brackets are must to enhance readability.
```

This project currently currently does not have code mandatory coding style for { } (except styles in .editorconfig).

**Comment by ilijamitkov** [comment]
Thanks for getting back first of all good job with the library and I'm also glad that the library is alive :)

Regarding code style comment I always prefer using curly braces because
a) Easy to modify
b) Easy to debug adding logs etc
c) Easy  to comment specific parts of the code that I may need it for production (again debugging)

However I usually tend to follow coding style when I'm adding to or modifying existing library so you decide :)

I'll also like to add docker setup for the integration tests, meaning changing the default credentials as well so it will be easier to contribute to the library?

**Pull request merged**
