### PR TITLE
Integrate GitLab group milestones

### PR DESCRIPTION
**Pull request by DTeuchert**
I also integrated the group milestones based on the [Gitlab API](https://docs.gitlab.com/ee/api/group_milestones.html).

Therefore I extract the milestone model into his own namespace. So the group-client and the project-client can us the same model.

### CODE REVIEW

**Comment by nmklotas** [comment]
very nice! thanks!

**Comment by DTeuchert** [comment]
You are welcome. It will be great if you could create a new NuGet.

**Comment by nmklotas** [comment]
Sure, it's published now. Changed some code to make publishing easier, we create tag and it will be deployed to NuGet, no code changes will be needed.

**Comment by DTeuchert** [comment]
Cool. I'm not sure but does it cause any issues, that you are using the 1.0.0 version in your csproj file. but your NuGet is released on 1.0.1 version?

**Comment by nmklotas** [comment]
I had to put something in csproj file:) ant that version is overwritten using pack script so no probs there

**Pull request merged**
