### PR TITLE
Basic Wikis API added.

### PR DESCRIPTION
**Pull request by TomSoldier**
I have added a basic Wikis API to the project, what i needed in my other project. Please check it, and if it's okay, merge it :)

### CODE REVIEW

**Comment by jetersen** [comment]
link to see current commit author: https://github.com/nmklotas/GitLabApiClient/commit/dfe34840a0613973818d2dfd2c9ecb5ce56f719f.patch

@TomSoldier 
You might want to set up an email alias on your GitHub account 🥇
https://help.github.com/articles/adding-an-email-address-to-your-github-account/

Or look into fixing your git user.email config 😅  
https://help.github.com/articles/setting-your-commit-email-address-in-git
then you would need to amend your commits: https://stackoverflow.com/a/3042512
after changing author

to get proper credit for your commits 🏆

**Review by jetersen — CHANGES_REQUESTED** [review]
The wiki client is not added to the main gitlab client.
Also could you fix file encoding to UTF8

**Comment by TomSoldier** [comment]
Added my another email address to this GitHub account. I hope i don't have to change my username.

**Comment by TomSoldier** [comment]
I don't need a Wikis API right now.. I'm closing this PR for now.

**Pull request closed without merging**
