### PR TITLE
Project import export

### PR DESCRIPTION
**Pull request by sandercox**
Added support to do Project exports and Project imports to move projects between two gitlab hosts

### CODE REVIEW

**Comment by casz** [comment]
Hi @sandercox 
I'd appreciate if you could increase the diff coverage 🙏

**Comment by sandercox** [comment]
Glad to help with that but have no clue how to setup the testing environment for this... 🙈

**Comment by casz** [comment]
@sandercox see https://github.com/nmklotas/GitLabApiClient/pull/99#issuecomment-569921414

I'll include in the contributiing.md 👍

**Comment by casz** [comment]
Would you mind resolving the conflicts?

**Comment by sandercox** [comment]
Updated the conflicts and added a unittest for export/import of a project. Hope this can be merged now!

**Review by jetersen — APPROVED** [review]

**Pull request merged**
