### PR TITLE
Feature/35 pipeline api

### PR DESCRIPTION
**Pull request by WebDucer**
- [x] Implementation of the API
- [x] Unit Tests for Query builder

### CODE REVIEW

**Comment by WebDucer** [comment]
@nmklotas I see no possibility to write the integration tests. For pipelines I need an running agent, that executes something and a project with `.gitlab-ci.yml` as pipeline definition. Any ideas?

**Comment by nmklotas** [comment]
@WebDucer Hi, thanks for the PR. For now you can use GitLabContainerFixture.cs to write integration test, I think travis will pick execute the test, or you can do it manually GitLabContainerFixture .cs will run the docker container probably if you have docker and using mac/linux. Integration tests are not really working for now, so you can skip that

**Comment by casz** [comment]
Regarding the work in #68 feel free to merge this one, I will rebase my work.

**Comment by WebDucer** [comment]
@nmklotas If you want to merge #68 first, I can rebase. I use projects name also a lot and now always _UrlEncode_ the names to be able to use them.

**Comment by nmklotas** [comment]
nice! thanks. pushing new version

**Comment by casz** [comment]
in #68 I ended removing most of the request objects as I seems like an indecisive pattern some places uses string, int others uses request objects where string int would suffice.

Request objects should be used for that parameters that is apart of the request body :)

For instance this uses string, int
https://github.com/nmklotas/GitLabApiClient/blob/fde4e25bb60c96e1b8d3266f6dc2b58a651e71b1/src/GitLabApiClient/PipelineClient.cs#L21-L22

However this one with the same need uses Request object
https://github.com/nmklotas/GitLabApiClient/blob/fde4e25bb60c96e1b8d3266f6dc2b58a651e71b1/src/GitLabApiClient/PipelineClient.cs#L39-L40

**Comment by WebDucer** [comment]
@casz You are right, we have to align the uses in body and URI.

My first implementation was more or less copied from the branch client (seems I copied too much). I will cleanup this one, as soon as your PR #68 is integrated.

**Comment by casz** [comment]
I already cleaned in up in #68 :)

**Comment by casz** [comment]
Just trying to nail the docker integration tests in travis and/or appveyor.

**Comment by casz** [comment]
I will most likely split the PR, focus on integration tests in another PR.

**Pull request merged**
