### PR TITLE
Added ClosedBy and ClosedAt property to issues and merge-requests

### LINKED ISSUE #32: Add 'Closed_~' Property in some models
Hello~

I need "Closed_at"  & "Closed_by" Property in 'Issue' (& 'Merge request') Model.

Can you add it ? 

I think type the next code somewhere.
```
        [JsonProperty("closed_at")]
        public DateTime? ClosedAt { get; set; }

        [JsonProperty("closed_by")]
        public string ClosedBy { get; set; }
```
Thanks~

### PR DESCRIPTION
**Pull request by dnagl**
Should fix #32

### CODE REVIEW

**Comment by nmklotas** [comment]
Thanks! Build fails, can you check? https://ci.appveyor.com/project/nmklotas/gitlabapiclient/builds/27252964

**Comment by dnagl** [comment]
Sure, I'll have a look at it

**Comment by dnagl** [comment]
The build is now fixed - I missed to add the System reference at these files.

**Comment by nmklotas** [comment]
Beautiful! thanks

**Pull request merged**
